typography_spectrum: 0.3135035599116236
color:
  brandStrength: 0.37670186231844127
  lightness: 0.8741167082916945
  saturation: 0.39690873329527676
  rhythmicContrast: 0.28189856349490583
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
layout_spectrum: 0.4331259753089398
author:
  name: Tovin Lapan
  email: tovinlapan@gmail.com
  url: 'http://tovinlapan.com'
logo: null
name: Tovin Lapan
favicon: null
title: Tovin Lapan
description: Freelance Journalist
