typography_spectrum: 0.43132795160636306
color:
  brandStrength: 0.9337805032264441
  lightness: 0.11535759991966188
  saturation: 0.1336138539481908
  rhythmicContrast: 0.9471541759558022
  brandColors:
    - '#962D3E'
    - '#343642'
    - '#979C9C'
    - '#F2EBC7'
    - '#348899'
layout_spectrum: 0.8387422263622284
author:
  name: Tovin Lapan
  email: tovinlapan@gmail.com
  url: 'http://tovinlapan.com'
logo: null
name: Tovin Lapan
navigation:
  - name: About Me
    id: 598af886-40b9-4195-843b-df513fbf7824
    type: content
  - name: Contact
    id: c6be684b-bd01-4fa6-8ce6-93e4c2f7e781
    type: content
  - name: Photography
    id: 61525eba-cab2-40c4-bd57-6a9243dae2e2
    type: content
favicon: null
title: Tovin Lapan
description: Freelance Journalist
