typography_spectrum: 0.7229914478957653
color:
  brandStrength: 0.31313735735602677
  lightness: 0.8536558945197612
  saturation: 0.4489056491293013
  rhythmicContrast: 0.8714782553724945
  brandColors:
    - '#595241'
    - '#B8AE9C'
    - '#FFFFFF'
    - '#ACCFCC'
    - '#8A0917'
layout_spectrum: 0.35436151875182986
author:
  name: Tovin Lapan
  email: tovinlapan@gmail.com
  url: ''
logo: null
name: Tovin Lapan
navigation:
  - name: About Me
    id: 598af886-40b9-4195-843b-df513fbf7824
    type: content
  - name: Contact
    id: c6be684b-bd01-4fa6-8ce6-93e4c2f7e781
    type: content
  - name: Photography
    id: 61525eba-cab2-40c4-bd57-6a9243dae2e2
    type: content
favicon: null
title: Freelance Journalist
description: ''
