typography_spectrum: 0.9247451403643936
color:
  brandStrength: 0.3634737685788423
  lightness: 0.516741054598242
  saturation: 0.9022195003926754
  rhythmicContrast: 0.9239209536463022
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
layout_spectrum: 0.7899526511318982
author:
  name: Tovin Lapan
  email: tovinlapan@gmail.com
  url: 'http://tovinlapan.com'
logo: null
name: Tovin Lapan – Freelance Journalist
navigation:
  - name: About Me
    id: 598af886-40b9-4195-843b-df513fbf7824
    type: content
  - name: Contact
    id: c6be684b-bd01-4fa6-8ce6-93e4c2f7e781
    type: content
  - name: Photography
    id: 61525eba-cab2-40c4-bd57-6a9243dae2e2
    type: content
favicon: null
title: Tovin Lapan – Freelance Journalist
description: Freelance Journalist
