typography_spectrum: 0.9356308632995933
color:
  brandStrength: 0.2862003173213452
  lightness: 0.33248888445086777
  saturation: 0.580538367619738
  rhythmicContrast: 0.15354240662418306
  brandColors:
    - '#595241'
    - '#B8AE9C'
    - '#FFFFFF'
    - '#ACCFCC'
    - '#8A0917'
layout_spectrum: 0.5174791244789958
author:
  name: Tovin Lapan
  email: tovinlapan@gmail.com
  url: 'http://tovinlapan.com'
logo: null
name: Tovin Lapan
navigation:
  - name: About Me
    id: 598af886-40b9-4195-843b-df513fbf7824
    type: content
  - name: Photography
    id: 61525eba-cab2-40c4-bd57-6a9243dae2e2
    type: content
  - name: Contact
    id: c6be684b-bd01-4fa6-8ce6-93e4c2f7e781
    type: content
favicon: null
title: Tovin Lapan
description: Freelance Journalist
