typography_spectrum: 0.7229914478957653
color:
  brandStrength: 0.31313735735602677
  lightness: 0.8536558945197612
  saturation: 0.4489056491293013
  rhythmicContrast: 0.8714782553724945
  brandColors:
    - '#595241'
    - '#B8AE9C'
    - '#FFFFFF'
    - '#ACCFCC'
    - '#8A0917'
layout_spectrum: 0.35436151875182986
author:
  name: Tovin Lapan
  email: tovinlapan@gmail.com
  url: ''
logo: null
name: Tovin&nbsp;Lapan
favicon: null
title: Tovin Lapan Freelance Journalist
